# 本文件用于模型训练完成后的评估，只进行模拟，不更新参数
includes:
- configs/stable_training/md17/train.yml
train: False
bond_dev_tol: 0.5
max_frac_unstable_threshold: 0.99
integrator: Langevin
results_dir: paper_stable_training_results
eval_model: post
temperature: 500.
steps: 2000 # 1 picosecond per epoch
timestep: 0.5
n_replicas: 256
n_dump: 2000  # 副本数
n_epochs: 1000 #corresponding to 1 ns（模拟总时长）

